import { Macondo } from "next/font/google";
import "./globals.css";
import { Header } from "./components/UI/Header";

const macondo = Macondo({
	weight: ["400"],
	// variable: "--font-macondo",
	subsets: ["latin"],
});

export const metadata = {
	title: "Next.js Introduction",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${macondo.className} antialiased`}>
				<Header />
				<main className="grid gap-24 mb-24">{children}</main>
			</body>
		</html>
	);
}
